makuake:
  urls:
    - https://www.makuake.com/project/go-dj-plus/
    - https://www.makuake.com/project/life-link/
    - https://www.makuake.com/project/sushi-suga/
    - https://www.makuake.com/project/kamikatsu-yakusou/

camp-fire:
  urls:

readyfor:
  urls:
